version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=naruto_db
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - spider_web

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '80:80'
    networks:
      - spider_web
networks:
  spider_web: {}
