-- https://naruto.fandom.com/pt-br/wiki/Selos_de_M%C3%A3o#Selos_b%C3%A1sicos
insert into seal (label)
values 
('???'),
('Passaro'), ('Javali'),
('Cao'), ('Dragao'),
('Boi'), ('Tigre'),
('Cobra'), ('Rato'),
('Cavalo'), ('Macaco'),
('Coelho'), ('Carneiro');

--https://naruto.fandom.com/pt-br/wiki/Categoria:Jutsu 
insert into classification (mark, label, description)
values
('R', 'Rank -', 'O Rank – (–ランク, – ranku) é utilizado no sistema de ranqueamento exclusivamente para técnicas, a fim de classificar as que não se encaixam na hierarquia padrão. Essas técnicas geralmente são provenientes de habilidades especiais do usuário — como linhagem sanguínea ou técnicas hiden — técnicas que utilizam animais, invocações, etc.'),
('R', 'Rank S', 'Rank S (Sランク, Esu ranku; Panini: "Classe S" ou "Classificação S"; Crunchyroll: "Ranque S")[1] é uma das seis classificações ninja. Ela é precedida pelo rank A. É geralmente utilizada na classificação de jutsu destinadas aos shinobi de nível jounin ou kage altamente experientes. As técnicas de rank S são quase sempre exclusivas para um único usuário, e tornam-se a sua marca registrada. As missões também podem ser classificadas com rank S, sendo os tipos de missão que pagam os mais altos valores e são as mais perigosas que um ninja pode realizar. Estas missões são exclusivamente atribuídas a jounin altamente habilidosos ou um grande esquadrão de ninjas. As missões de rank S pagam no mínimo 1,000,000 ryō. "Rank S" é também uma designação dada à ninjas renegados extremamente poderosos, ganhando um lugar no Bingo Book da sua aldeia de origem.[2] A organização Akatsuki foi composta por criminosos rank S.'),
('R', 'Rank A', 'Rank A (Aランク, Ē ranku; Dublagem: "Nível A")[1] é uma das seis classificações ninja. Ela é precedida pelo Rank B e seguida pelo Rank S. É geralmente utilizada na classificação de técnicas destinadas aos ninjas de nível Kage ou jounin. Técnicas Rank A são geralmente muito úteis, mas precisam de treinamento intensivo antes de serem dominadas. Algumas técnicas de Rank A também representam um risco para o usuário, resultando em sua classificação como kinjutsu. Existem também missões de Rank A. Estas estão relacionadas aos interesses pessoais da aldeia ou do país, e são extremamente difíceis e perigosas de completar, normalmente atribuídas à um jounin. Missões Rank A pagam entre 150,000 e 1,000,000 ryō.'),
('R', 'Rank B', 'O Rank B (Bランク, Bī ranku; Dublagem: "Nível B"; Crunchyroll: "Ranque B")[1] é uma das seis classificações ninja. Ela é precedida pelo rank C e seguida pelo rank A. É geralmente utilizada na classificação de técnicas destinadas aos shinobi de nível jounin ou chuunin. As técnicas de rank B são normalmente úteis, e podem ser aprendidas de forma relativamente fácil, com tempo suficiente, tal como a Técnica dos Clones das Sombras. Existem também missões deste rank. Essas são, geralmente, atribuídas a jounin ou chuunin. Elas podem envolver espionagem ou assassinatos, e é esperado que os ninjas batalhem contra ninjas inimigos durante o curso da missão. Missões Rank B pagam entre 80,000 e 200,000 ryō.'),
('R', 'Rank C', 'Rank C (Cランク, Shī ranku; Dublagem: "Nível C")[1] é uma das seis classificações ninja. Ela é precedida pelo Rank D e seguida pelo Rank B. É geralmente utilizada na classificação de técnicas destinadas aos ninjas de nível chuunin. Técnicas Rank C são muitas das vezes uma das primeiras técnicas que os ninjas aprendem que necessitam de uma certa quantidade de treinamento. Existem também missões de Rank C. Estas missões são geralmente atribuídas à chuunin, ou, em alguns casos, aos genin. Estas missões incluem trabalhar como guarda-costas e caçar animais selvagens, todas as quais provavelmente irão representar algum risco para o ninja. O único exemplo conhecido de uma missão Rank C foi a atribuição do Time Kakashi para escoltar Tazuna até o País das Ondas. Depois que se descobriu que Tazuna tinha assassinos atrás dele, a missão foi declarada por Kakashi Hatake para ser Rank B ou mesmo Rank A. As missões deste rank pagam entre 30,000 e 100,000 ryō.'),
('R', 'Rank D', 'Rank D (Dランク, Dī ranku; Dublagem: "Nível D")[1] é uma das seis classificações ninja. Ele é precedido pelo Rank E e é seguido pelo Rank C. Ele é geralmente usado na classificação de técnicas destinadas aos ninjas de nível genin. Técnicas de Rank D são muitas vezes uma das primeiras técnicas que os ninjas aprendem depois de deixar a Academia. Existem também missões de Rank D, a classificação mais baixa que uma missão pode receber. Essas missões geralmente são atribuídas a genin. Naruto Uzumaki descreve as missões Rank D como não sendo missões reais por se tratar de tarefas tão simples como encontrar animais desaparecidos e capinar jardins. Missões Rank D pagam entre 5,000 e 50,000 ryō.'),
('R', 'Rank E', 'Rank E (Eランク, Ī ranku) é uma das seis classificações ninja, sendo a mais baixa dentre todas. Ele é seguido pelo Rank D e usado exclusivamente na classificação de técnicas destinadas aos estudantes da Academia. Um número de técnicas Rank E deve ser aprendido antes do ninja poder se graduar, e elas só são difíceis no sentido de que os alunos podem não ter aprendido a controlar adequadamente o seu chakra. Com o tempo, técnicas de Rank E como a Técnica de Substituição tornam-se uma segunda natureza para ninjas experientes.');


-- https://naruto.fandom.com/pt-br/wiki/Categoria:Jutsu
insert into classification (mark, label, description)
values
('1', 'Ninjutsu', 'Ninjutsu (忍術; literalmente significa: "Técnicas Ninjas") que refere-se à quase toda técnica e permite ao usuário fazer algo que ele seria capaz de fazer de outra maneira, incluindo o uso de armas. Diferente de genjutsu, que faz o alvo ver ilusões, os efeitos do ninjutsu são reais. Eles variam grandemente no propósito, com os ninjutsu mais simples sendo usados para tarefas como transformar o usuário ou permitindo-o desviar de ataques. Essas técnicas frequentemente são a segunda natureza de shinobi experientes, que podem usá-las à vontade. Ninjutsu mais complexos manipulam o ambiente ou utilizam elementos, respectivamente servindo a tarefas como curar os outros ou manipular Mudanças da Natureza. Ninjutsu, na maioria do tempo, conta com chakra e selos de mão para ser eficiente. As mãos são postas em posições sequenciais que moldam e manipulam o chakra da maneira necessária para realizar uma técnica. Porém isso não é sempre preciso e algumas técnicas tornam-se a segunda natureza de ninjas experientes, que podem ser realizadas à vontade.'),
('1', 'Taijutsu', 'Taijutsu (体術; literalmente significa: "Técnicas Corporais"; Panini: "Técnicas de Combate"; "Técnicas de Luta Corporal")[1][2] é uma forma básica de técnicas e refere-se à qualquer técnica que envolva artes marciais ou a otimização das habilidades humanas naturais. O taijutsu é executado ao acessar diretamente as energias físicas e mentais do usuário, contando com a resistência e força ganhas através do treinamento. O taijutsu tipicamente não requer chakra, apesar do chakra poder ser usado para fortificar suas técnicas, e dispensa selos de mão na maioria das vezes, ocasionalmente fazendo certos gestos ou poses, além de ser muito mais rápido de usar do que ninjutsu ou genjutsu. Taijutsu é colocado simplesmente como combate corpo-a-corpo e pode ser regionalizado, como o "boxe" (ボクシング, bokushingu) sendo reconhecido como um estilo de taijutsu estrangeiro por um ninja de Konohagakure.[3]'),
('1', 'Genjutsu', 'Genjutsu (幻術; literalmente significa: "Técnicas Ilusórias"; Panini: "Técnica de Ilusão" ou "Técnica Ilusória"; Dublagem: "Jutsu de Ilusão")[1][2] são técnicas que são empregadas do mesmo modo que o ninjutsu, requerendo converter estamina em chakra usando selos de mão e o controle de chakra.[3] Isso é um método simples de criar um tipo de alucinação por hipnose.[4] Além disso, genjutsu se enquadra claramente no Estilo Yin por sua capacidade de criar formas a partir do nada.[5]'),
('1', 'Shinjutsu', 'Shinjutsu (神術; literalmente significa: "Técnica Divina") são habilidades que superam o ninjutsu e senjutsu, sendo comparáveis a milagres divinos. Shibai Ootsutsuki, que consumiu incontáveis Frutos de Chakra ao longo de milênios, acumulou em si informação genética o suficiente para evoluir até se tornar em uma divindade, obtendo o shinjutsu. Sem a necessidade de selos de mão, como no ninjutsu, Shibai podia criar tempestades com um aceno de sua mão e gerar raios com seu rugido.[1]');

-- https://naruto.fandom.com/pt-br/wiki/Mudan%C3%A7a_da_Natureza
insert into classification (mark, label, description)
values
('E', 'Estilo Fogo', '(火遁, Katon) — é forte contra Vento, mas fraco contra Água.'),
('E', 'Estilo Vento','(風遁, Fuuton) — é forte contra Trovão, mas fraco contra Fogo.'),
('E', 'Estilo Terra','(土遁, Doton) — é forte contra Água, mas fraco contra Trovão.'),
('E', 'Estilo Raio', '(雷遁, Raiton) — é forte contra Terra, mas fraco contra Vento.'),
('E', 'Estilo Água', '(水遁, Suiton) — é forte contra Fogo, mas fraco contra Terra.');
